SEARCH_KEYS = [
    'explains',
    'count',
    'quotes',
    'news',
    'nav',
    'lists',
    'researchReports',
    'screenerFieldResults',
    'totalTime',
    'timeTakenForQuotes',
    'timeTakenForNews',
    'timeTakenForAlgowatchlist',
    'timeTakenForPredefinedScreener',
    'timeTakenForCrunchbase',
    'timeTakenForNav',
    'timeTakenForResearchReports',
    'timeTakenForScreenerField',
    'timeTakenForCulturalAssets',
    'timeTakenForSearchLists',
]

QUOTE_KEYS = [
    'language',
    'region',
    'quoteType',
    'typeDisp',
    'quoteSourceName',
    'triggerable',
    'customPriceAlertConfidence',
    'currency',
    'marketState',
    # 'postMarketChangePercent',
    # 'postMarketPrice',
    # 'postMarketChange',
    'regularMarketChange',
    'regularMarketDayHigh',
    'regularMarketDayRange',
    'regularMarketDayLow',
    'regularMarketVolume',
    'regularMarketPreviousClose',
    'bid',
    'ask',
    'bidSize',
    'askSize',
    'fullExchangeName',
    'financialCurrency',
    'regularMarketOpen',
    'averageDailyVolume3Month',
    'averageDailyVolume10Day',
    'fiftyTwoWeekLowChange',
    'fiftyTwoWeekLowChangePercent',
    'fiftyTwoWeekRange',
    'fiftyTwoWeekHighChange',
    'fiftyTwoWeekHighChangePercent',
    'fiftyTwoWeekLow',
    'fiftyTwoWeekHigh',
    'fiftyTwoWeekChangePercent',
    # 'dividendDate',
    'earningsTimestamp',
    'earningsTimestampStart',
    'earningsTimestampEnd',
    'earningsCallTimestampStart',
    'earningsCallTimestampEnd',
    'isEarningsDateEstimate',
    'trailingAnnualDividendRate',
    'trailingPE',
    # 'dividendRate',
    'trailingAnnualDividendYield',
    # 'dividendYield',
    'epsTrailingTwelveMonths',
    'epsForward',
    'epsCurrentYear',
    'priceEpsCurrentYear',
    'sharesOutstanding',
    'bookValue',
    'fiftyDayAverage',
    'fiftyDayAverageChange',
    'fiftyDayAverageChangePercent',
    'twoHundredDayAverage',
    'twoHundredDayAverageChange',
    'twoHundredDayAverageChangePercent',
    'marketCap',
    'forwardPE',
    'priceToBook',
    'sourceInterval',
    'exchangeDataDelayedBy',
    # 'ipoExpectedDate',
    'averageAnalystRating',
    'tradeable',
    'cryptoTradeable',
    'hasPrePostMarketData',
    'firstTradeDateMilliseconds',
    'priceHint',
    'shortName',
    'longName',
    'corporateActions',
    # 'postMarketTime',
    'regularMarketTime',
    'exchange',
    'messageBoardId',
    'exchangeTimezoneName',
    'exchangeTimezoneShortName',
    'gmtOffSetMilliseconds',
    'market',
    'esgPopulated',
    'regularMarketChangePercent',
    'regularMarketPrice',
    # 'displayName',
    'symbol',
]

ASSET_PROFILE_KEYS = [
    'address1',
    'city',
    'state',
    'zip',
    'country',
    'phone',
    'website',
    'industry',
    'industryKey',
    'industryDisp',
    'sector',
    'sectorKey',
    'sectorDisp',
    'longBusinessSummary',
    'fullTimeEmployees',
    'companyOfficers',
    'auditRisk',
    'boardRisk',
    'compensationRisk',
    'shareHolderRightsRisk',
    'overallRisk',
    'governanceEpochDate',
    'compensationAsOfEpochDate',
    'executiveTeam',
    'maxAge',
]

QUOTE_TYPE_KEYS = [
    'exchange',
    'quoteType',
    'symbol',
    'underlyingSymbol',
    'shortName',
    'longName',
    'firstTradeDateEpochUtc',
    'timeZoneFullName',
    'timeZoneShortName',
    'uuid',
    'messageBoardId',
    'gmtOffSetMilliseconds',
    'maxAge',
]

SUMMARY_PROFILE_KEYS = [
    'address1',
    'city',
    'state',
    'zip',
    'country',
    'phone',
    'website',
    'industry',
    'industryKey',
    'industryDisp',
    'sector',
    'sectorKey',
    'sectorDisp',
    'longBusinessSummary',
    'fullTimeEmployees',
    'companyOfficers',
    'executiveTeam',
    'maxAge',
]

SUMMARY_DETAIL_KEYS = [
    'maxAge',
    'priceHint',
    'previousClose',
    'open',
    'dayLow',
    'dayHigh',
    'regularMarketPreviousClose',
    'regularMarketOpen',
    'regularMarketDayLow',
    'regularMarketDayHigh',
    'dividendRate',
    'dividendYield',
    'exDividendDate',
    'payoutRatio',
    'beta',
    'trailingPE',
    'forwardPE',
    'volume',
    'regularMarketVolume',
    'averageVolume',
    'averageVolume10days',
    'averageDailyVolume10Day',
    'bid',
    'ask',
    'bidSize',
    'askSize',
    'marketCap',
    'fiftyTwoWeekLow',
    'fiftyTwoWeekHigh',
    'allTimeHigh',
    'allTimeLow',
    'priceToSalesTrailing12Months',
    'fiftyDayAverage',
    'twoHundredDayAverage',
    'trailingAnnualDividendRate',
    'trailingAnnualDividendYield',
    'currency',
    'fromCurrency',
    'toCurrency',
    'lastMarket',
    'coinMarketCapLink',
    'algorithm',
    'tradeable',
]

INCOME_STATEMENT_HISTORY_KEYS = [
    'maxAge',
    'endDate',
    'totalRevenue',
    'costOfRevenue',
    'grossProfit',
    'researchDevelopment',
    'sellingGeneralAdministrative',
    'nonRecurring',
    'otherOperatingExpenses',
    'totalOperatingExpenses',
    'operatingIncome',
    'totalOtherIncomeExpenseNet',
    'ebit',
    'interestExpense',
    'incomeBeforeTax',
    'incomeTaxExpense',
    'minorityInterest',
    'netIncomeFromContinuingOps',
    'discontinuedOperations',
    'extraordinaryItems',
    'effectOfAccountingCharges',
    'otherItems',
    'netIncome',
    'netIncomeApplicableToCommonShares',
]

ESG_SCORES_KEYS = [
    'maxAge',
    'totalEsg',
    'environmentScore',
    'socialScore',
    'governanceScore',
    'ratingYear',
    'ratingMonth',
    'highestControversy',
    'peerCount',
    'esgPerformance',
    'peerGroup',
    'peerEsgScorePerformance',
    'peerGovernancePerformance',
    'peerSocialPerformance',
    'peerEnvironmentPerformance',
    'peerHighestControversyPerformance',
    'percentile',
    'environmentPercentile',
    'socialPercentile',
    'governancePercentile',
    'adult',
    'alcoholic',
    'animalTesting',
    'catholic',
    'controversialWeapons',
    'smallArms',
    'furLeather',
    'gambling',
    'gmo',
    'militaryContract',
    'nuclear',
    'pesticides',
    'palmOil',
    'coal',
    'tobacco',
]

PRICE_KEYS = [
    'maxAge',
    # 'preMarketChangePercent',
    # 'preMarketChange',
    # 'preMarketTime',
    # 'preMarketPrice',
    # 'preMarketSource',
    # 'postMarketChangePercent',
    # 'postMarketChange',
    # 'postMarketTime',
    # 'postMarketPrice',
    # 'postMarketSource',
    'regularMarketChangePercent',
    'regularMarketChange',
    'regularMarketTime',
    'priceHint',
    'regularMarketPrice',
    'regularMarketDayHigh',
    'regularMarketDayLow',
    'regularMarketVolume',
    'regularMarketPreviousClose',
    'regularMarketSource',
    'regularMarketOpen',
    'exchange',
    'exchangeName',
    'exchangeDataDelayedBy',
    'marketState',
    'quoteType',
    'symbol',
    'underlyingSymbol',
    'shortName',
    'longName',
    'currency',
    'quoteSourceName',
    'currencySymbol',
    'fromCurrency',
    'toCurrency',
    'lastMarket',
    'marketCap',
]

DEFAULT_KEY_STATISTICS_KEYS = [
    'maxAge',
    'priceHint',
    'enterpriseValue',
    'forwardPE',
    'profitMargins',
    'floatShares',
    'sharesOutstanding',
    'sharesShort',
    'sharesShortPriorMonth',
    'sharesShortPreviousMonthDate',
    'dateShortInterest',
    'sharesPercentSharesOut',
    'heldPercentInsiders',
    'heldPercentInstitutions',
    'shortRatio',
    'shortPercentOfFloat',
    'beta',
    'impliedSharesOutstanding',
    'category',
    'bookValue',
    'priceToBook',
    'fundFamily',
    'legalType',
    'lastFiscalYearEnd',
    'nextFiscalYearEnd',
    'mostRecentQuarter',
    'earningsQuarterlyGrowth',
    'netIncomeToCommon',
    'trailingEps',
    'forwardEps',
    'lastSplitFactor',
    'enterpriseToRevenue',
    'enterpriseToEbitda',
    '52WeekChange',
    'SandP52WeekChange',
    'lastDividendValue',
    'lastDividendDate',
    'latestShareClass',
    'leadInvestor',
]

FINANCIAL_DATA_KEYS = [
    'maxAge',
    'currentPrice',
    'targetHighPrice',
    'targetLowPrice',
    'targetMeanPrice',
    'targetMedianPrice',
    'recommendationMean',
    'recommendationKey',
    'numberOfAnalystOpinions',
    'totalCash',
    'totalCashPerShare',
    'ebitda',
    'totalDebt',
    'quickRatio',
    'currentRatio',
    'totalRevenue',
    'debtToEquity',
    'revenuePerShare',
    'returnOnAssets',
    'returnOnEquity',
    'grossProfits',
    'freeCashflow',
    'operatingCashflow',
    'earningsGrowth',
    'revenueGrowth',
    'grossMargins',
    'ebitdaMargins',
    'operatingMargins',
    'profitMargins',
    'financialCurrency',
]

CALENDAR_EVENTS_EARNING_KEYS = [
    'earningsDate',
    'earningsCallDate',
    'isEarningsDateEstimate',
    'earningsAverage',
    'earningsLow',
    'earningsHigh',
    'revenueAverage',
    'revenueLow',
    'revenueHigh',
]

SEC_FILING_KEYS = [
    'date',
    'epochDate',
    'type',
    'title',
    'edgarUrl',
    'exhibits',
    'maxAge',
]

UPGRADE_DOWNGRADE_HISTORY_KEYS = [
    'epochGradeDate',
    'firm',
    'toGrade',
    'fromGrade',
    'action',
    'priceTargetAction',
    'currentPriceTarget',
    'priorPriceTarget',
]

OWNERSHIP_KEYS = [
    'maxAge',
    'reportDate',
    'organization',
    'pctHeld',
    'position',
    'value',
    'pctChange',
]

MAJOR_HOLDERS_BREAKDOWN_KEYS = [
    'maxAge',
    'insidersPercentHeld',
    'institutionsPercentHeld',
    'institutionsFloatPercentHeld',
    'institutionsCount',
]

TRANSACTION_KEYS = [
    'maxAge',
    'shares',
    # 'value',
    'filerUrl',
    'transactionText',
    'filerName',
    'filerRelation',
    'moneyText',
    'startDate',
    'ownership',
]

HOLDER_KEYS = [
    'maxAge',
    'name',
    'relation',
    'url',
    'transactionDescription',
    'latestTransDate',
    # 'positionDirect',
    # 'positionDirectDate',
]

NET_SHARE_PURCHASE_ACIVITY_KEYS = [
    'maxAge',
    'period',
    'buyInfoCount',
    'buyInfoShares',
    'sellInfoCount',
    'netInfoCount',
    'netInfoShares',
    'totalInsiderShares',
]

EARNINGS_HISTORY_KEYS = [
    'maxAge',
    'epsActual',
    'epsEstimate',
    'epsDifference',
    'surprisePercent',
    'quarter',
    'currency',
    'period',
]

EARNINGS_TREND_KEYS = [
    'maxAge',
    'period',
    'endDate',
    'growth',
    'earningsEstimate',
    'revenueEstimate',
    'epsTrend',
    'epsRevisions',
]

RECOMMENDATIONS_TREND_KEYS = [
    'period',
    'strongBuy',
    'buy',
    'hold',
    'sell',
    'strongSell',
]

OPTIONS_KEYS = [
    'underlyingSymbol',
    'expirationDates',
    'strikes',
    'hasMiniOptions',
    'quote',
    'options',
]

INSIGHTS_KEYS = [
    'symbol',
    'instrumentInfo',
    'companySnapshot',
    'recommendation',
    'upsell',
    'upsellSearchDD',
    'events',
    'reports',
    'sigDevs',
    'secReports',
]

MARKET_SUMMARY_KEYS = [
    'language',
    'region',
    'quoteType',
    'typeDisp',
    # 'quoteSourceName',
    'triggerable',
    'customPriceAlertConfidence',
    'sourceInterval',
    'exchangeDataDelayedBy',
    'exchangeTimezoneName',
    'exchangeTimezoneShortName',
    'gmtOffSetMilliseconds',
    'esgPopulated',
    'tradeable',
    'cryptoTradeable',
    'hasPrePostMarketData',
    'firstTradeDateMilliseconds',
    # 'priceHint',
    'regularMarketChange',
    'regularMarketChangePercent',
    'regularMarketTime',
    'regularMarketPrice',
    'regularMarketPreviousClose',
    'exchange',
    'market',
    'fullExchangeName',
    # 'longName',
    'marketState',
    'shortName',
    'symbol',
]

TRENDING_KEYS = ['count', 'quotes', 'jobTimestamp', 'startInterval']

CURRENCY_KEYS = ['shortName', 'longName', 'symbol', 'localLongName']
